name = "MaterialPointSolver"
uuid = "dc4aa359-7d89-437d-91bb-f4b330c522c1"
authors = ["Zenan Huo <zenan.huo@outlook.com>"]
version = "0.4.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
SysInfo = "90a7ee08-a23f-48b9-9006-0e0e2a9e4608"

[compat]
Adapt = "4.0"
BenchmarkTools = "1.5"
CodecZlib = "0.7"
DelimitedFiles = "1.9"
HDF5 = "0.17"
KernelAbstractions = "0.9"
ProgressMeter = "1.10"
StatsBase = "0.34"
Suppressor = "0.2"
SysInfo = "0.3"
julia = "1.11"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[extensions]
MaterialPointSolverAMDGPUExt = "AMDGPU"
MaterialPointSolverCUDAExt = "CUDA"
MaterialPointSolverMetalExt = "Metal"
MaterialPointSolveroneAPIExt = "oneAPI"
MaterialPointSolverDebugExt = "WGLMakie"

[extras]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[targets]
test = ["Test", "BenchmarkTools", "DelimitedFiles"]