[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
MaterialPointSolver = "dc4aa359-7d89-437d-91bb-f4b330c522c1"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
MaterialPointSolver = {path = ".."}

[compat]
Documenter = "1.8"
DocumenterVitepress = "0.1"
WGLMakie = "0.11"