[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
MaterialPointSolver = "dc4aa359-7d89-437d-91bb-f4b330c522c1"

[sources]
MaterialPointSolver = {path = ".."}

[compat]
Documenter = "1.16"
DocumenterVitepress = "0.2"